### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by zvs001** [Airbitz/edge-react-gui#258]
FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':react-native-fast-crypto:externalNativeBuildRelease'.
> java.io.FileNotFoundException: /home/zvs001/work/maya/vault-logic-wallet-mobile/node_modules/react-native-fast-crypto/android/.externalNativeBuild/cmake/release/armeabi-v7a/android_gradle_build.json (No such file or directory)
```

**Comment by paullinator** [comment]
Can you describe your exact build command to build the app. I assume this was android? Were you running from within Android Studio or command line?

**Comment by zvs001** [comment]
It appeared after my second pull. It was looking like no breaking changes were.
It was fixed after i do another git clone.
