### ISSUE TITLE
suggestion to update instructions to remove package.lock.json before npm i

### ISSUE THREAD

**Issue by annjieching** [Airbitz/edge-react-gui#271]
Hi, I had an issue where `npm install` froze as follows: 

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v9.3.0
npm verb npm-session 96cbb8fb306ead19
npm info lifecycle edge-react-gui@0.2.0~preinstall: edge-react-gui@0.2.0
npm info lifecycle react-native-http@1.0.0~prepack: react-native-http@1.0.0
⸨ ░░░░░░░░░░░░░░░░░⸩ ⠧ loadIdealTree:loadAllDepsIntoIdealTree: info lifecycle react-nativ
```

After removing package.lock.json, the problem has gone away. The rest of the installation is taking an extremely long time, for some reason or another.

**Comment by alvarosilvac** [comment]
Same problem here. But removing the package.lock.json didn't solve my problem.

**Comment by paullinator** [comment]
Please downgrade npm to 5.5.1

If you are using nvm then 

nvm install 8.9.3. 

Do NOT use 8.9.4 as that installs npm 5.6.0 which breaks the build.
