### ISSUE TITLE
a problem on npm install

### ISSUE THREAD

**Issue by chinaRong** [Airbitz/edge-react-gui#599]
I had an issue where npm install froze as follows:
`
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

scrypt@6.0.3

 preinstall /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/scrypt
node node-scrypt-preinstall.js

bcoin-native@0.0.23 install /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/bcoin-native
node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/bcoin-native
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

 keccak@1.4.0 install /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/keccak
 npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."

keccak@1.4.0 rebuild /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/keccak
node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/keccak
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-04-21T12_14_12_139Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

fsevents@1.2.0 install /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/fsevents
node install

[fsevents] Success: "/Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

scrypt@6.0.3 install /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/scrypt
node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/Documents/edge-react-gui/edge-react-gui/node_modules/scrypt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN react-native-background-task@0.2.1 requires a peer of react-native-background-fetch@2.0.x but none is installed. You must install peer dependencies yourself.
npm WARN react-native-fs@2.9.12 requires a peer of react@^16.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-fs@2.9.12 requires a peer of prop-types@15.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-fast-crypto@1.5.5 requires a peer of react-native@^0.47.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-level-fs@3.0.1 requires a peer of asyncstorage-down@>=3.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN disklet@0.2.5 requires a peer of react-native@^0.47.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcoin-native@0.0.23 (node_modules/bcoin-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcoin-native@0.0.23 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! 
`

**Comment by paullinator** [comment]
nom has been unreliable for us. Please use `yarn` instead to install. Recommend v 1.3.2 or higher.

**Comment by chinaRong** [comment]
I install yarn instead of npm , but it still break as follows:
`
warning Error running install script for optional dependency: "/Users/admin/Library/Caches/Yarn/v1/.tmp/df416a18a0c768bd716aae96821b15b3.20d6a3e9f060131325c1958aa5aed61c39711dc9.prepare/node_modules/bcoin-native: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/admin/Library/Caches/Yarn/v1/.tmp/df416a18a0c768bd716aae96821b15b3.20d6a3e9f060131325c1958aa5aed61c39711dc9.prepare/node_modules/bcoin-native
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.3 | darwin | x64
gyp http GET https://dist.npmjs.org/v8.9.3/node-v8.9.3-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Request.emit (events.js:211:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:878:8)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)
gyp ERR! System Darwin 16.7.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/admin/Library/Caches/Yarn/v1/.tmp/df416a18a0c768bd716aae96821b15b3.20d6a3e9f060131325c1958aa5aed61c39711dc9.prepare/node_modules/bcoin-native
[6/6] ⠂ uws
[-/6] ⠂ waiting...
[3/6] ⠂ bcoin-native: not ok
[4/6] ⠂ leveldown
[-/6] ⠄ waiting...

`

**Comment by paullinator** [comment]
I've seen this odd error before and the solution ended up being a lot of dancing on your head. Try any or all of the following:

1. Reboot the computer
2. Wipe out the repo, re-clone, then yarn
3. I assume you're on MacOS. Reinstall Xcode with command line tools, reboot, and log back in.

Super sorry for the troubles. React native has given us a lot of build problems that have not been resolved with any known means other than trying whacky stuff like above.

**Comment by chinaRong** [comment]
thanks for @paullinator  answer my question. I resolved it by restall all things.
